z3 = "/Users/docinf/Developer/qifac/.venv/bin/z3"
z3tracer = "/Users/docinf/Developer/qifac/submodules/smt2utils/target/release/z3tracer"
lib_qids = [
    "Maps",
    "totalorder",
    "Message",
    "SetBijectivity",
    "Sequences",
    "Arrays",
    "SequencesOfMaps",
    "FloatingSeqTest",
    "Multisets",
    "Sets",
    "orderedmap",
    "BitsetLemmas",
    "DebugAccumulator",
    "mathematics",
    "map",
    "MutableVec",
    "lexical",
    "MallocAccounting",
    "LinearOption",
    "PackedIntsLib",
]

