from pathlib import Path
from typing import List, Sequence, TextIO

class SmtLibCommand: ...

class SmtLibScript:
    commands: List[SmtLibCommand]
    def filter_by_command_name(self, command_name: str) -> Sequence[SmtLibCommand]: ...
    def to_file(self, fname: Path, daggify: bool = True) -> None: ...
    def serialize(self, buffer: TextIO, daggify: bool = True) -> None: ...
